package de.avalax.mtg_insight.domain.model.card;

public enum Ability {
    DEATHTOUCH, DEFENDER, DOUBLE_STRIKE, FIRST_STRIKE, FLASH,
    FLYING, HASTE, HEXPROOF, INDESTRUCTIBLE, INTIMIDATE, LANDWALK,
    LIFELINK, PROTECTION, REACH, SHROUD, TRAMPLE, VIGILANCE
}
